# Generated by Django 4.2.24 on 2026-04-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Testator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DECEASED', 'Deceased'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('will_document', models.FileField(blank=True, null=True, upload_to='wills/')),
                ('blockchain_tx', models.CharField(blank=True, max_length=255, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('pq_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiaries', models.ManyToManyField(to='dashboard.beneficiary')),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.testator')),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('place_of_death', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('date_of_death', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verified', models.BooleanField(default=True)),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.testator')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.beneficiary')),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.testator')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.testator'),
        ),
    ]
