# Generated by Django 4.2.24 on 2026-04-20 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathcertificate',
            name='aadhaar',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar must be exactly 12 digits', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='testator',
            name='aadhaar',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar must be exactly 12 digits', regex='^\\d{12}$')]),
        ),
    ]
