# Generated by Django 4.2.24 on 2026-04-20 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_deathcertificate_aadhaar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdistribution',
            old_name='share_percentage',
            new_name='share',
        ),
        migrations.RemoveField(
            model_name='assetdistribution',
            name='testator',
        ),
        migrations.AddField(
            model_name='assetdistribution',
            name='will',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.will'),
        ),
    ]
