# Generated by Django 4.2.24 on 2026-04-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_share_percentage_assetdistribution_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdistribution',
            name='will',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.will'),
        ),
    ]
