# Generated by Django 4.2.24 on 2026-04-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_assetdistribution_will'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathcertificate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deathcertificate',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='deathcertificate',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='deathcertificate',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='deathcertificate',
            name='testator',
        ),
        migrations.RemoveField(
            model_name='deathcertificate',
            name='verified',
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='will',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.will'),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='aadhaar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='certificate_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='date_of_death',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='place_of_death',
            field=models.CharField(max_length=100),
        ),
    ]
