# Generated by Django 4.2.24 on 2026-04-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_deathcertificate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathcertificate',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='date_of_registration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
