# Generated by Django 4.2.24 on 2026-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_deathcertificate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathcertificate',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
