# Generated by Django 4.2.24 on 2026-04-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_deathcertificate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathcertificate',
            name='place_of_death',
        ),
    ]
