# Generated by Django 4.2.24 on 2026-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_deathcertificate_place_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='wallet_address',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42),
        ),
        migrations.AddField(
            model_name='testator',
            name='wallet_address',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42),
        ),
    ]
