# Generated by Django 4.2.24 on 2026-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_beneficiary_wallet_address_testator_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
