# Generated by Django 4.2.24 on 2026-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_beneficiary_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdistribution',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='assetdistribution',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
